'use strict';
const $=id=>document.getElementById(id), C=AtelierCore, assets=new Map();
let serial=0, doc={sheets:[newSheet()],page:0}, tool='move', selected=null, snap=true, guide=true, ink='#384b43', brush=12, busy=false;
let undo=[],redo=[],crop=null,gesture=null,layerPage=0,downloadURL=null,toastTimer;
const pointers=new Map(), canvas=$('canvas'), overlay=$('overlay'), ctx=canvas.getContext('2d'), ui=overlay.getContext('2d');
function uid(){return ++serial}
function newSheet(w=595,h=842){return{w,h,bg:null,grid:1,layers:[]}}
function sheet(){return doc.sheets[doc.page]}
function layer(){return sheet().layers.find(l=>l.id===selected)}
function makeCanvas(w,h){const c=document.createElement('canvas');c.width=w;c.height=h;return c}
function register(c){const id=uid();assets.set(id,c);return id}
function makeLayer(asset,name='画像'){const c=assets.get(asset);return{id:uid(),asset,name,w:c.width,h:c.height,x:sheet().w/2,y:sheet().h/2,scale:1,rotation:0,visible:true,opacity:1,frame:null}}
function snapshot(){return JSON.stringify({doc,selected})}
function collect(){const used=new Set();for(const state of [snapshot(),...undo,...redo])for(const p of JSON.parse(state).doc.sheets)for(const l of p.layers)used.add(l.asset);for(const id of assets.keys())if(!used.has(id))assets.delete(id)}
function checkpoint(){undo.push(snapshot());if(undo.length>25)undo.shift();redo=[]}
function changed(){crop=null;render();collect()}
function restore(state){const d=JSON.parse(state);doc=d.doc;selected=d.selected;crop=null;gesture=null;pointers.clear();render()}
function history(back){if(busy)return;const from=back?undo:redo,to=back?redo:undo;if(!from.length)return;to.push(snapshot());restore(from.pop());collect();toast(back?'元に戻しました':'やり直しました')}
function toast(t){clearTimeout(toastTimer);$('toast').textContent=t;$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,3300)}
function setBusy(value,text){busy=value;$('app').inert=value;if(text)$('hint').textContent=text}
function closePanel(){$('modal').innerHTML=''}
function panel(title,html){$('modal').innerHTML=`<div class="shade ${title==='レイヤー'?'layer-drawer':''}"><section class="panel" role="dialog" aria-modal="true" aria-label="${title}"><div class="panel-head"><h2>${title}</h2><button id="closePanel" aria-label="閉じる">×</button></div>${html}</section></div>`;$('closePanel').onclick=closePanel;$('closePanel').focus()}
function escapeHTML(t){return t.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function layout(){const p=sheet(),r=$('workspace').getBoundingClientRect(),pad=r.height<240?20:36,scale=Math.min((r.width-pad)/p.w,(r.height-pad)/p.h);$('paper').style.width=Math.max(1,p.w*scale)+'px';$('paper').style.height=Math.max(1,p.h*scale)+'px'}
function render(){const p=sheet();if(canvas.width!==p.w||canvas.height!==p.h){canvas.width=overlay.width=p.w;canvas.height=overlay.height=p.h}C.render(ctx,p,assets);$('dimensions').textContent=`${p.w} × ${p.h} px${p.bg?'':' · 透過'}`;$('page').textContent=`${doc.page+1} / ${doc.sheets.length}`;$('prev').disabled=doc.page===0;$('next').disabled=doc.page===doc.sheets.length-1;$('undo').disabled=!undo.length;$('redo').disabled=!redo.length;$('empty').hidden=p.layers.length>0||tool==='pen';document.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===tool));options();layout();drawOverlay();hint()}
function hint(){const l=layer();$('hint').textContent=tool==='crop'?'指で四角く囲む →「切り抜く」で確定':tool==='pen'?'選択中のレイヤーに描画 · 空のときは描画レイヤーを追加':tool==='eraser'?'選択したレイヤーだけを消します':l?`${l.name} · 1本指で移動／2本指で拡大・回転`:'画像をタップして選択 · 追加でまとめて読み込み'}
function drawOverlay(){ui.clearRect(0,0,overlay.width,overlay.height);const scale=overlay.width/Math.max(1,overlay.clientWidth),p=sheet();ui.lineWidth=scale;ui.strokeStyle='#418b80';if(guide&&p.grid>1){ui.save();ui.setLineDash([5*scale,4*scale]);for(const r of C.cells(p.w,p.h,p.grid))ui.strokeRect(r.x,r.y,r.w,r.h);ui.restore()}const l=layer();if(l&&tool==='move'){ui.save();if(l.frame){ui.strokeStyle='#d09b58';ui.strokeRect(l.frame.x,l.frame.y,l.frame.w,l.frame.h)}ui.translate(l.x,l.y);ui.rotate(l.rotation*Math.PI/180);ui.strokeStyle='#388a77';ui.strokeRect(-l.w*l.scale/2,-l.h*l.scale/2,l.w*l.scale,l.h*l.scale);for(const [x,y] of [[-1,-1],[1,-1],[1,1],[-1,1]]){ui.fillStyle='white';ui.fillRect(x*l.w*l.scale/2-3*scale,y*l.h*l.scale/2-3*scale,6*scale,6*scale);ui.strokeRect(x*l.w*l.scale/2-3*scale,y*l.h*l.scale/2-3*scale,6*scale,6*scale)}ui.restore()}if(crop){const r=cropRect();ui.fillStyle='#398a7433';ui.fillRect(r.x,r.y,r.w,r.h);ui.strokeStyle='#327d68';ui.strokeRect(r.x,r.y,r.w,r.h)}}
function options(){if(tool==='pen'||tool==='eraser'){$('options').innerHTML=`<input type="color" id="ink" aria-label="ペンの色" value="${ink}" ${tool==='eraser'?'disabled':''}><label>太さ <input id="brush" type="range" min="1" max="100" value="${brush}" aria-label="ペンの太さ"><span id="brushValue">${brush}</span></label><button id="newPaint">新レイヤー</button>`;$('ink').oninput=e=>ink=e.target.value;$('brush').oninput=e=>{brush=+e.target.value;$('brushValue').textContent=brush};$('newPaint').onclick=()=>{checkpoint();addPaint();changed()};return}if(tool==='crop'){$('options').innerHTML='<button id="confirmCrop">切り抜く</button><button id="cancelCrop">取消</button><small>選択レイヤーを四角く切抜</small>';$('confirmCrop').onclick=applyCrop;$('cancelCrop').onclick=()=>{crop=null;drawOverlay()};return}$('options').innerHTML=`<button id="snapping" class="${snap?'on':''}">吸着 ${snap?'入':'切'}</button><button id="smaller" aria-label="縮小">−</button><button id="larger" aria-label="拡大">＋</button><button id="rotate">回転 15°</button><button id="resetAngle">角度 0°</button>`;$('snapping').onclick=()=>{snap=!snap;options()};$('smaller').onclick=()=>transform(.9,0);$('larger').onclick=()=>transform(1.1,0);$('rotate').onclick=()=>transform(1,15);$('resetAngle').onclick=()=>{const l=layer();if(!l)return;checkpoint();l.rotation=0;changed()}}
function transform(f,a){const l=layer();if(!l){toast('画像を選んでください');return}checkpoint();l.scale=Math.max(.01,Math.min(30,l.scale*f));l.rotation=(l.rotation+a)%360;changed()}
function setTool(t){if(busy)return;if(t==='add'){$('files').click();return}if(t==='align'){alignPanel();return}if(t==='split'){splitPanel();return}if(t==='save'){savePanel();return}tool=t;crop=null;render()}
function point(e){const r=overlay.getBoundingClientRect();return{x:(e.clientX-r.left)*sheet().w/r.width,y:(e.clientY-r.top)*sheet().h/r.height}}
function topAt(p){return [...sheet().layers].reverse().find(l=>C.hit(l,p))}
function addPaint(){const a=register(makeCanvas(sheet().w,sheet().h)),l=makeLayer(a,'描画');sheet().layers.push(l);selected=l.id;return l}
function writable(l){const src=assets.get(l.asset),c=makeCanvas(src.width,src.height);c.getContext('2d').drawImage(src,0,0);l.asset=register(c);return c.getContext('2d')}
function brushLine(l,a,b){const c=assets.get(l.asset).getContext('2d'),p=C.localPoint(l,a),q=C.localPoint(l,b);c.save();if(l.frame){const corners=[[l.frame.x,l.frame.y],[l.frame.x+l.frame.w,l.frame.y],[l.frame.x+l.frame.w,l.frame.y+l.frame.h],[l.frame.x,l.frame.y+l.frame.h]].map(([x,y])=>C.localPoint(l,{x,y}));c.beginPath();corners.forEach((r,i)=>i?c.lineTo(r.x,r.y):c.moveTo(r.x,r.y));c.closePath();c.clip()}c.globalCompositeOperation=tool==='eraser'?'destination-out':'source-over';c.strokeStyle=ink;c.fillStyle=ink;c.lineWidth=brush/l.scale;c.lineCap='round';c.lineJoin='round';c.beginPath();c.moveTo(p.x,p.y);c.lineTo(q.x,q.y);c.stroke();if(p.x===q.x&&p.y===q.y){c.beginPath();c.arc(p.x,p.y,brush/l.scale/2,0,Math.PI*2);c.fill()}c.restore();C.render(ctx,sheet(),assets)}
function beginTransform(){const l=layer();if(!l)return;const pts=[...pointers.values()];gesture={type:'move',id:l.id,base:{x:l.x,y:l.y,scale:l.scale,rotation:l.rotation},pts:pts.map(p=>({...p})),checked:gesture?.checked||false}}
function snapLayer(l){if(!snap)return;const p=sheet(),threshold=8*p.w/Math.max(1,overlay.clientWidth),cs=C.cells(p.w,p.h,p.grid),xs=[0,p.w,p.w/2,...cs.flatMap(r=>[r.x,r.x+r.w/2,r.x+r.w])],ys=[0,p.h,p.h/2,...cs.flatMap(r=>[r.y,r.y+r.h/2,r.y+r.h])];const angle=l.rotation*Math.PI/180,hw=(Math.abs(Math.cos(angle))*l.w+Math.abs(Math.sin(angle))*l.h)*l.scale/2,hh=(Math.abs(Math.sin(angle))*l.w+Math.abs(Math.cos(angle))*l.h)*l.scale/2;function best(v,half,guides){let d=threshold+1,shift=0;for(const edge of [v,v-half,v+half])for(const line of guides){const diff=line-edge;if(Math.abs(diff)<d){d=Math.abs(diff);shift=diff}}return d<=threshold?v+shift:v}l.x=best(l.x,hw,xs);l.y=best(l.y,hh,ys)}
overlay.addEventListener('pointerdown',e=>{if(busy||$('modal').children.length)return;e.preventDefault();overlay.setPointerCapture(e.pointerId);const p=point(e);pointers.set(e.pointerId,p);if(tool==='move'){if(pointers.size===1){const found=topAt(p);selected=found?.id??null;gesture=null}beginTransform();render();return}if(pointers.size>1)return;if(tool==='crop'){crop={start:p,end:p};gesture={type:'crop'};drawOverlay();return}if(tool==='pen'||tool==='eraser'){let l=layer();if(l&&!l.visible){toast('非表示のレイヤーです');pointers.clear();return}if(!l&&tool==='eraser'){toast('消すレイヤーを選んでください');return}checkpoint();if(!l)l=addPaint();else writable(l);gesture={type:'paint',id:l.id,last:p};brushLine(l,p,p);$('empty').hidden=true}});
overlay.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId)||!gesture)return;e.preventDefault();const p=point(e);pointers.set(e.pointerId,p);if(gesture.type==='crop'){crop.end=p;drawOverlay();return}if(gesture.type==='paint'){if(pointers.size!==1)return;const l=sheet().layers.find(l=>l.id===gesture.id);brushLine(l,gesture.last,p);gesture.last=p;return}const l=layer();if(!l)return;const pts=[...pointers.values()],g=gesture;if(!g.checked){checkpoint();g.checked=true}if(pts.length>=2&&g.pts.length>=2){const [a,b]=g.pts,[c,d]=pts,oldMid={x:(a.x+b.x)/2,y:(a.y+b.y)/2},mid={x:(c.x+d.x)/2,y:(c.y+d.y)/2},dist=Math.hypot(b.x-a.x,b.y-a.y),factor=Math.hypot(d.x-c.x,d.y-c.y)/Math.max(1,dist),angle=Math.atan2(d.y-c.y,d.x-c.x)-Math.atan2(b.y-a.y,b.x-a.x);l.scale=Math.max(.01,Math.min(30,g.base.scale*factor));const actual=l.scale/g.base.scale,dx=g.base.x-oldMid.x,dy=g.base.y-oldMid.y;l.rotation=g.base.rotation+angle*180/Math.PI;l.x=mid.x+(dx*Math.cos(angle)-dy*Math.sin(angle))*actual;l.y=mid.y+(dx*Math.sin(angle)+dy*Math.cos(angle))*actual}else{l.x=g.base.x+p.x-g.pts[0].x;l.y=g.base.y+p.y-g.pts[0].y;snapLayer(l)}C.render(ctx,sheet(),assets);drawOverlay()});
function endPointer(e){pointers.delete(e.pointerId);if(gesture?.type==='move'&&pointers.size){beginTransform();return}if(!pointers.size){gesture=null;render();collect()}}
overlay.addEventListener('pointerup',endPointer);overlay.addEventListener('pointercancel',endPointer);
function cropRect(){const p=sheet(),x=Math.max(0,Math.min(crop.start.x,crop.end.x)),y=Math.max(0,Math.min(crop.start.y,crop.end.y));return{x:Math.round(x),y:Math.round(y),w:Math.max(0,Math.round(Math.min(p.w,Math.max(crop.start.x,crop.end.x))-x)),h:Math.max(0,Math.round(Math.min(p.h,Math.max(crop.start.y,crop.end.y))-y))}}
function applyCrop(){const l=layer();if(!l||!crop){toast('レイヤーを選び、残す範囲を囲んでください');return}const r=cropRect();if(r.w<2||r.h<2){toast('切り抜く範囲が小さすぎます');return}const c=makeCanvas(r.w,r.h),cx=c.getContext('2d');cx.translate(-r.x,-r.y);C.drawLayer(cx,l,assets);checkpoint();Object.assign(l,{asset:register(c),w:r.w,h:r.h,x:r.x+r.w/2,y:r.y+r.h/2,scale:1,rotation:0,opacity:1,frame:null});crop=null;tool='move';changed();toast('選択した範囲を切り抜きました')}
async function readImage(file){const url=URL.createObjectURL(file);try{const img=new Image();img.src=url;await img.decode();if(img.naturalWidth*img.naturalHeight>24000000)throw Error('24メガピクセルを超える画像です');const c=makeCanvas(img.naturalWidth,img.naturalHeight);c.getContext('2d').drawImage(img,0,0);return c}finally{URL.revokeObjectURL(url)}}
$('files').onchange=async e=>{const files=[...e.target.files];e.target.value='';if(!files.length)return;if(files.length+doc.sheets.reduce((n,p)=>n+p.layers.length,0)>60){toast('1作品につき画像・描画は60レイヤーまでです');return}closePanel();setBusy(true,'画像を読み込み中…');const added=[],failed=[];let pixels=[...assets.values()].reduce((n,c)=>n+c.width*c.height,0);try{for(const f of files){try{if(f.size>32*1024*1024)throw Error('32MBを超えています');const c=await readImage(f);if(pixels+c.width*c.height>60000000)throw Error('作品の画像容量が上限を超えます');pixels+=c.width*c.height;added.push({c,name:f.name})}catch(err){failed.push(`${f.name}: ${err.message}`)}}if(added.length){checkpoint();for(const {c,name} of added){const l=makeLayer(register(c),name);l.scale=Math.min(sheet().w*.85/c.width,sheet().h*.85/c.height);sheet().layers.push(l);selected=l.id}changed()}}finally{setBusy(false);render()}if(failed.length){panel('読み込み結果',`<p>${added.length}枚を追加しました。${failed.length}枚を読み込めませんでした。</p><p>${escapeHTML(failed[0])}</p><p class="quiet">大きな画像は縮小してから再度追加してください。</p>`)}else if(added.length>1){alignPanel(added.length)}};
function alignPanel(added){panel('画像をそろえる',`<p>${added?`${added}枚を追加しました。`:'画像を同じ枠サイズにそろえます。'}「全画像をカード化」は全シートの画像を読み込み順に並べ直します。</p><div class="row"><label>1枚の幅<input id="cardW" type="number" value="595" min="1" max="2048"></label><label>高さ<input id="cardH" type="number" value="842" min="1" max="2048"></label></div><div class="row"><select id="perPage" aria-label="1シートの枚数"><option value="6">6枚ずつ（2列×3段）</option><option value="2">2枚ずつ（2列×1段）</option><option value="4">4枚ずつ（2列×2段）</option><option value="9">9枚ずつ（3列×3段）</option></select><select id="fit" aria-label="画像の合わせ方"><option value="contain">全体を収める</option><option value="cover">枠いっぱいにする</option></select></div><button id="batch" class="primary full">全画像をカード化・シートに分ける</button><button id="currentAlign" class="option full">今のシート内だけ均等に整列</button><p class="quiet">全体を収める：余白あり／枠いっぱい：はみ出す部分を隠します。元画像は保持します。</p>`);$('batch').onclick=()=>batchArrange(+$('cardW').value,+$('cardH').value,+$('perPage').value,$('fit').value);$('currentAlign').onclick=()=>{const n=+$('perPage').value;if(sheet().layers.length>n){toast(`現在${sheet().layers.length}枚あります。全画像をカード化してください`);return}checkpoint();sheet().grid=n;const cs=C.cells(sheet().w,sheet().h,n);sheet().layers.forEach((l,i)=>Object.assign(l,C.placement({width:l.w,height:l.h},cs[i],$('fit').value)));closePanel();changed()}}
function batchArrange(w,h,n,fit){const ls=doc.sheets.flatMap(p=>p.layers);if(!ls.length){toast('先に画像を追加してください');return}const [cols,rows]=C.layouts[n];if(!Number.isInteger(w)||!Number.isInteger(h)||w<1||h<1||w*cols>4096||h*rows>4096||w*h*n>12000000){toast('シートは各辺4096px・合計1200万画素以内にしてください');return}checkpoint();const pages=[];ls.forEach((l,i)=>{if(i%n===0){const p=newSheet(w*cols,h*rows);p.grid=n;pages.push(p)}const p=pages.at(-1),cell=C.cells(p.w,p.h,n)[i%n];Object.assign(l,C.placement({width:l.w,height:l.h},cell,fit));p.layers.push(l)});doc.sheets=pages;doc.page=0;selected=pages[0].layers[0]?.id;closePanel();changed();toast(`${ls.length}枚を${pages.length}シートに整列しました`)}
function splitPanel(){panel('分割ガイド',`<p>選んだ分割数でガイドを表示します。画像を動かすと枠の端・中央に吸着します。</p><div class="grid three">${[1,2,4,6,9].map(n=>`<button class="option" data-grid="${n}">${n===1?'なし':n+'分割'}</button>`).join('')}</div><label><input id="guideVisible" type="checkbox" ${guide?'checked':''}>ガイドを表示</label><p>完成済みの6枚シートは、画像をキャンバスいっぱいに合わせてから「6分割」→「保存」で切り出せます。</p><button id="fitCanvas" class="option full">選択画像にキャンバスを合わせる</button>`);document.querySelectorAll('[data-grid]').forEach(b=>b.onclick=()=>{checkpoint();sheet().grid=+b.dataset.grid;guide=true;closePanel();changed()});$('guideVisible').onchange=e=>{guide=e.target.checked;drawOverlay()};$('fitCanvas').onclick=()=>{const l=layer();if(!l){toast('画像を選んでください');return}if(l.w>4096||l.h>4096||l.w*l.h>12000000){toast('画像が大きすぎます。キャンバスは各辺4096px以内です');return}checkpoint();sheet().w=l.w;sheet().h=l.h;Object.assign(l,{x:l.w/2,y:l.h/2,rotation:0,scale:1,frame:null});closePanel();changed()}}
function documentPanel(){panel('キャンバスと背景',`<p>幅・高さを固定して編集します。サイズ変更は中央を基準に行います。</p><div class="grid"><button class="option" data-size="595,842">カード 595×842</button><button class="option" data-size="842,595">横カード 842×595</button><button class="option" data-size="1080,1080">正方形 1080×1080</button><button class="option" data-size="1190,2526">カード6枚シート</button></div><div class="row"><label>幅<input id="width" type="number" min="1" max="4096" value="${sheet().w}"></label><label>高さ<input id="height" type="number" min="1" max="4096" value="${sheet().h}"></label></div><div class="row"><label><input id="transparent" type="checkbox" ${sheet().bg?'':'checked'}>背景を透過</label><input type="color" id="background" aria-label="背景色" value="${sheet().bg||'#ffffff'}"></div><button id="applyDocument" class="primary full">適用する</button><div class="grid" style="margin-top:8px"><button id="loadProject" class="option">編集データを開く</button><button id="newProject" class="option">新しい作品</button></div>`);document.querySelectorAll('[data-size]').forEach(b=>b.onclick=()=>{const [w,h]=b.dataset.size.split(',');$('width').value=w;$('height').value=h});$('background').oninput=()=>{$('transparent').checked=false};$('applyDocument').onclick=()=>{const w=+$('width').value,h=+$('height').value;if(!Number.isInteger(w)||!Number.isInteger(h)||w<1||h<1||w>4096||h>4096||w*h>12000000){toast('各辺1〜4096px・合計1200万画素以内で指定してください');return}checkpoint();const p=sheet(),dx=(w-p.w)/2,dy=(h-p.h)/2;p.layers.forEach(l=>{l.x+=dx;l.y+=dy;if(l.frame){l.frame.x+=dx;l.frame.y+=dy}});p.w=w;p.h=h;p.bg=$('transparent').checked?null:$('background').value;closePanel();changed()};$('loadProject').onclick=()=>{$('projectFile').click()};$('newProject').onclick=()=>{panel('新しい作品','<p>現在の編集を閉じます。必要な場合は、先に「保存」から編集データを保存してください。</p><button id="confirmNew" class="primary full">新しい作品を作る</button>');$('confirmNew').onclick=()=>{checkpoint();doc={sheets:[newSheet()],page:0};selected=null;closePanel();changed()}}}
function layersPanel(){const ls=[...sheet().layers].reverse(),size=4,max=Math.max(1,Math.ceil(ls.length/size));layerPage=Math.min(layerPage,max-1);panel('レイヤー',`<p class="quiet">上にある画像ほど手前です。選んだレイヤーだけを編集します。</p><div id="layerList"></div><div class="paging"><button id="layerPrev">‹</button><span>${layerPage+1} / ${max}</span><button id="layerNext">›</button></div><div class="layer-actions"><button id="upLayer">上へ</button><button id="downLayer">下へ</button><button id="duplicate">複製</button><button id="deleteLayer">削除</button></div><button id="addDrawing" class="option full">描画レイヤーを追加</button>`);for(const l of ls.slice(layerPage*size,layerPage*size+size)){const row=document.createElement('div');row.className='layer-row'+(selected===l.id?' chosen':'');const thumb=document.createElement('canvas');thumb.width=thumb.height=34;thumb.className='thumb';const c=assets.get(l.asset),z=Math.min(34/l.w,34/l.h);thumb.getContext('2d').drawImage(c,(34-l.w*z)/2,(34-l.h*z)/2,l.w*z,l.h*z);const pick=document.createElement('button');pick.className='pick';pick.textContent=l.name;pick.onclick=()=>{selected=l.id;render();layersPanel()};const vis=document.createElement('button');vis.textContent=l.visible?'◉':'○';vis.setAttribute('aria-label',l.visible?'非表示にする':'表示する');vis.onclick=()=>{checkpoint();l.visible=!l.visible;changed();layersPanel()};row.append(thumb,pick,vis);$('layerList').append(row)}$('layerPrev').disabled=layerPage===0;$('layerNext').disabled=layerPage>=max-1;$('layerPrev').onclick=()=>{layerPage--;layersPanel()};$('layerNext').onclick=()=>{layerPage++;layersPanel()};$('upLayer').onclick=()=>reorder(1);$('downLayer').onclick=()=>reorder(-1);$('duplicate').onclick=()=>{const l=layer();if(!l)return;if(doc.sheets.flatMap(p=>p.layers).length>=60){toast('60レイヤーまでです');return}checkpoint();const copy={...l,id:uid(),name:l.name+' 複製',frame:l.frame?{...l.frame}:null};sheet().layers.push(copy);selected=copy.id;changed();layersPanel()};$('deleteLayer').onclick=()=>{if(!layer())return;checkpoint();sheet().layers=sheet().layers.filter(l=>l.id!==selected);selected=sheet().layers.at(-1)?.id??null;changed();layersPanel()};$('addDrawing').onclick=()=>{checkpoint();addPaint();closePanel();tool='pen';changed()}}
function reorder(delta){const ls=sheet().layers,i=ls.findIndex(l=>l.id===selected),j=i+delta;if(i<0||j<0||j>=ls.length)return;checkpoint();[ls[i],ls[j]]=[ls[j],ls[i]];changed();layersPanel()}
function savePanel(){panel('画像・編集データを保存',`<p>ガイドと選択枠は書き出されません。複数PNGは1つのZIPにまとめます。</p><label><input id="exportTransparent" type="checkbox" ${sheet().bg?'':'checked'}>背景色を含めず透過PNGで出力</label><label><input id="skipBlank" type="checkbox" checked>何も配置されていない枠を除く</label><div class="grid"><button class="option" id="exportCurrent">今のシート PNG</button><button class="option" id="exportSplit">今のシートを分割</button><button class="primary" id="exportAllSplit">全シートを分割 ZIP</button><button class="option" id="exportLayers">画像を1枚ずつ ZIP</button><button class="option" id="exportSheets">全シート PNG ZIP</button><button class="option" id="exportProject">編集データを保存</button></div><p class="quiet">編集データを保存すると、画像・レイヤー・位置を再編集できます。自動保存はしません。</p>`);for(const [id,kind] of [['exportCurrent','current'],['exportSplit','split'],['exportAllSplit','allSplit'],['exportLayers','layers'],['exportSheets','sheets'],['exportProject','project']])$(id).onclick=()=>exportFiles(kind,$('exportTransparent').checked,$('skipBlank').checked)}
function blobPNG(c){return new Promise((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(Error('PNGを書き出せませんでした')),'image/png'))}
function overlaps(l,r){const a=l.rotation*Math.PI/180,hw=(Math.abs(Math.cos(a))*l.w+Math.abs(Math.sin(a))*l.h)*l.scale/2,hh=(Math.abs(Math.sin(a))*l.w+Math.abs(Math.cos(a))*l.h)*l.scale/2,b=l.frame||{x:l.x-hw,y:l.y-hh,w:2*hw,h:2*hh};return l.visible&&b.x<r.x+r.w&&b.x+b.w>r.x&&b.y<r.y+r.h&&b.y+b.h>r.y}
async function exportFiles(kind,transparent,skipBlank){closePanel();setBusy(true,'書き出し中…');try{const files=[];async function add(name,c){const b=await blobPNG(c);files.push({name,data:new Uint8Array(await b.arrayBuffer())})}if(kind==='project'){const ids=new Set(doc.sheets.flatMap(p=>p.layers.map(l=>l.asset))),packed={version:1,doc,assets:{}};for(const id of ids)packed.assets[id]=assets.get(id).toDataURL('image/png');showDownload(new Blob([JSON.stringify(packed)],{type:'application/json'}),'atelier-project.json','編集データを準備しました');return}
 if(kind==='layers'){let n=0;for(const p of doc.sheets)for(const l of p.layers){if(!l.visible)continue;const box=l.frame||{x:0,y:0,w:p.w,h:p.h},c=makeCanvas(box.w,box.h),cx=c.getContext('2d');if(!transparent&&p.bg){cx.fillStyle=p.bg;cx.fillRect(0,0,c.width,c.height)}cx.translate(-box.x,-box.y);C.drawLayer(cx,l,assets);await add(`image_${String(++n).padStart(3,'0')}.png`,c);c.width=c.height=1}}
 else{const pages=kind==='current'||kind==='split'?[sheet()]:doc.sheets;let n=0;for(const p of pages){const c=makeCanvas(p.w,p.h);C.render(c.getContext('2d'),p,assets,transparent);if(kind==='split'||kind==='allSplit'){for(const box of C.cells(p.w,p.h,p.grid)){if(skipBlank&&!p.layers.some(l=>overlaps(l,box)))continue;const tile=makeCanvas(box.w,box.h);tile.getContext('2d').drawImage(c,box.x,box.y,box.w,box.h,0,0,box.w,box.h);await add(`card_${String(++n).padStart(3,'0')}.png`,tile);tile.width=tile.height=1}}else await add(`sheet_${String(++n).padStart(3,'0')}.png`,c);c.width=c.height=1}}
 if(!files.length){toast('出力する画像がありません');return}if(kind==='current')showDownload(new Blob([files[0].data],{type:'image/png'}),'atelier.png','PNGを準備しました');else showDownload(new Blob([C.zip(files)],{type:'application/zip'}),'atelier-images.zip',`${files.length}枚のPNGをZIPにまとめました`)
 }catch(e){toast('保存に失敗しました：'+e.message)}finally{setBusy(false);render()}}
function showDownload(blob,name,summary){if(downloadURL)URL.revokeObjectURL(downloadURL);downloadURL=URL.createObjectURL(blob);panel('保存の準備ができました',`<p>${summary}</p><a id="download" class="download" download="${name}">ファイルに保存</a><button id="share" class="option full">共有・写真へ保存</button><p class="quiet">ZIPは「ファイル」に保存して開くと、PNGをまとめて取り出せます。編集を続ける場合は右上の×で閉じます。</p>`);$('download').href=downloadURL;$('share').onclick=async()=>{try{const file=new File([blob],name,{type:blob.type});if(navigator.canShare?.({files:[file]})){await navigator.share({files:[file]})}else toast('「ファイルに保存」を使ってください')}catch(e){if(e.name!=='AbortError')toast('共有できませんでした。「ファイルに保存」を使ってください')}}}
function validateProject(data){if(data.version!==1||!data.doc||!Array.isArray(data.doc.sheets)||!data.doc.sheets.length||data.doc.sheets.length>60||!data.assets)throw Error('対応していない編集データです');let count=0;for(const p of data.doc.sheets){if(!Number.isInteger(p.w)||!Number.isInteger(p.h)||p.w<1||p.h<1||p.w>4096||p.h>4096||p.w*p.h>12000000||!C.layouts[p.grid]||!Array.isArray(p.layers)||!(p.bg===null||/^#[0-9a-f]{6}$/i.test(p.bg)))throw Error('キャンバス情報が不正です');for(const l of p.layers){count++;if(typeof l.name!=='string'||typeof l.visible!=='boolean'||!Number.isInteger(l.id)||!Number.isInteger(l.asset)||!String(data.assets[l.asset]).startsWith('data:image/png;base64,')||!['w','h','x','y','scale','rotation','opacity'].every(k=>Number.isFinite(l[k]))||l.w<=0||l.h<=0||l.w>8192||l.h>8192||l.scale<=0||l.scale>30||l.opacity<0||l.opacity>1)throw Error('レイヤー情報が不正です');if(l.frame&&(!['x','y','w','h'].every(k=>Number.isFinite(l.frame[k]))||l.frame.w<=0||l.frame.h<=0))throw Error('枠情報が不正です')}}if(count>60)throw Error('レイヤーが多すぎます')}
$('projectFile').onchange=async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;panel('編集データを開く','<p>現在の編集を、選んだファイルに切り替えます。必要な場合は、先に現在の編集データを保存してください。</p><button id="confirmLoad" class="primary full">選んだ編集データを開く</button>');$('confirmLoad').onclick=async()=>{closePanel();setBusy(true,'編集データを読み込み中…');try{if(f.size>120*1024*1024)throw Error('ファイルが大きすぎます');const data=JSON.parse(await f.text());validateProject(data);const incoming=new Map(),map=new Map();let pixels=0;for(const old of new Set(data.doc.sheets.flatMap(p=>p.layers.map(l=>l.asset)))){const image=new Image();image.src=data.assets[old];await image.decode();pixels+=image.naturalWidth*image.naturalHeight;if(pixels>60000000)throw Error('画像容量が上限を超えています');const c=makeCanvas(image.naturalWidth,image.naturalHeight);c.getContext('2d').drawImage(image,0,0);const id=uid();incoming.set(id,c);map.set(old,id)}for(const p of data.doc.sheets)for(const l of p.layers){l.id=uid();l.asset=map.get(l.asset)}checkpoint();incoming.forEach((c,id)=>assets.set(id,c));doc=data.doc;doc.page=0;selected=null;changed();toast('編集データを開きました')}catch(err){toast('読み込めませんでした：'+err.message)}finally{setBusy(false);render()}}};
$('document').onclick=documentPanel;$('layers').onclick=layersPanel;$('undo').onclick=()=>history(true);$('redo').onclick=()=>history(false);$('prev').onclick=()=>{doc.page--;selected=null;crop=null;render()};$('next').onclick=()=>{doc.page++;selected=null;crop=null;render()};$('addSheet').onclick=()=>{if(doc.sheets.length>=60){toast('60シートまでです');return}checkpoint();doc.sheets.push(newSheet(sheet().w,sheet().h));doc.page=doc.sheets.length-1;selected=null;changed()};document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));new ResizeObserver(layout).observe($('workspace'));
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'&&!/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)){e.preventDefault();history(!e.shiftKey)}});
render();
