(function(root){
'use strict';
const layouts={1:[1,1],2:[2,1],4:[2,2],6:[2,3],9:[3,3]};
function cells(w,h,count){const [cols,rows]=layouts[count]||layouts[1];return Array.from({length:cols*rows},(_,i)=>{let col=i%cols,row=Math.floor(i/cols),x=Math.round(col*w/cols),y=Math.round(row*h/rows);return{x,y,w:Math.round((col+1)*w/cols)-x,h:Math.round((row+1)*h/rows)-y}})}
function fit(aw,ah,box,mode='contain'){return mode==='cover'?Math.max(box.w/aw,box.h/ah):Math.min(box.w/aw,box.h/ah)}
function placement(asset,box,mode='contain'){return{x:box.x+box.w/2,y:box.y+box.h/2,scale:fit(asset.width,asset.height,box,mode),rotation:0,frame:{...box}}}
function localPoint(layer,p){const a=-layer.rotation*Math.PI/180,dx=p.x-layer.x,dy=p.y-layer.y;return{x:(dx*Math.cos(a)-dy*Math.sin(a))/layer.scale+layer.w/2,y:(dx*Math.sin(a)+dy*Math.cos(a))/layer.scale+layer.h/2}}
function hit(layer,p){if(!layer.visible)return false;if(layer.frame&&(p.x<layer.frame.x||p.y<layer.frame.y||p.x>layer.frame.x+layer.frame.w||p.y>layer.frame.y+layer.frame.h))return false;const q=localPoint(layer,p);return q.x>=0&&q.y>=0&&q.x<=layer.w&&q.y<=layer.h}
function drawLayer(ctx,l,assets){if(!l.visible)return;const asset=assets.get(l.asset);if(!asset)return;ctx.save();if(l.frame){ctx.beginPath();ctx.rect(l.frame.x,l.frame.y,l.frame.w,l.frame.h);ctx.clip()}ctx.globalAlpha=l.opacity??1;ctx.translate(l.x,l.y);ctx.rotate(l.rotation*Math.PI/180);ctx.scale(l.scale,l.scale);ctx.drawImage(asset,-l.w/2,-l.h/2,l.w,l.h);ctx.restore()}
function render(ctx,sheet,assets,transparent=false){ctx.clearRect(0,0,sheet.w,sheet.h);if(sheet.bg&&!transparent){ctx.fillStyle=sheet.bg;ctx.fillRect(0,0,sheet.w,sheet.h)}for(const l of sheet.layers)drawLayer(ctx,l,assets)}
const table=Array.from({length:256},(_,n)=>{for(let i=0;i<8;i++)n=(n&1)?0xedb88320^(n>>>1):n>>>1;return n>>>0});
function crc32(data){let c=0xffffffff;for(const b of data)c=table[(c^b)&255]^(c>>>8);return(c^0xffffffff)>>>0}
function zip(files){const chunks=[],directory=[];let offset=0;const encode=new TextEncoder();for(const f of files){const name=encode.encode(f.name),data=f.data,crc=crc32(data),head=new Uint8Array(30+name.length),h=new DataView(head.buffer);h.setUint32(0,0x04034b50,true);h.setUint16(4,20,true);h.setUint16(6,0x800,true);h.setUint16(12,33,true);h.setUint32(14,crc,true);h.setUint32(18,data.length,true);h.setUint32(22,data.length,true);h.setUint16(26,name.length,true);head.set(name,30);chunks.push(head,data);const dir=new Uint8Array(46+name.length),d=new DataView(dir.buffer);d.setUint32(0,0x02014b50,true);d.setUint16(4,20,true);d.setUint16(6,20,true);d.setUint16(8,0x800,true);d.setUint16(14,33,true);d.setUint32(16,crc,true);d.setUint32(20,data.length,true);d.setUint32(24,data.length,true);d.setUint16(28,name.length,true);d.setUint32(42,offset,true);dir.set(name,46);directory.push(dir);offset+=head.length+data.length}const size=directory.reduce((n,d)=>n+d.length,0),end=new Uint8Array(22),e=new DataView(end.buffer);e.setUint32(0,0x06054b50,true);e.setUint16(8,files.length,true);e.setUint16(10,files.length,true);e.setUint32(12,size,true);e.setUint32(16,offset,true);const all=[...chunks,...directory,end],out=new Uint8Array(offset+size+22);let at=0;for(const a of all){out.set(a,at);at+=a.length}return out}
const api={layouts,cells,fit,placement,localPoint,hit,drawLayer,render,crc32,zip};if(typeof module!=='undefined')module.exports=api;else root.AtelierCore=api;
})(typeof window!=='undefined'?window:this);
