(()=>{
const herbs=[
  ['ラベンダー',0,40],['カモミール',1,45],['ミント',2,35],['セージ',3,55],['ローズマリー',4,60],
  ['セントジョーンズワート',5,70],['エキナセア',6,75],['レモンバーム',7,55],['カレンデュラ',8,60],['エルダー',9,80],
  ['ローズヒップ',10,85],['リンデン',11,90],['クローバー',12,50],['ネトル',13,65],['スミレ',14,70]
].map((x,i)=>({name:x[0],sprite:x[1],seedCost:x[2],unlocked:i<3,grow:(i<3?20+i*22:0),harvest:0}));
const tools={drying:true,cauldron:true,chop:false,mortar:false,basket:true};
const toolCost={chop:250,mortar:300};
const recipes=[{name:'安らぎの茶',cost:90,unlocked:true},{name:'香草の煎じ液',cost:120,unlocked:false},{name:'乾燥薬草包',cost:140,unlocked:false},{name:'粉末ブレンド',cost:180,unlocked:false}];
let money=120, minutes=8*60, day=1, raw=0, processed=0, products=[0,0,0,0,0], activeTab='seeds';
let work={drying:0,cauldron:0,chop:0,mortar:0};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const moneyEl=$('#money'),timeEl=$('#time'),dateEl=$('#date'),garden=$('#gardenGrid'),productRow=$('#productRow'),customerRow=$('#customerRow'),message=$('#message'),basketCount=$('#basketCount');
function herbSpan(i,extra=''){return `<span class="herb h${i} ${extra}" aria-hidden="true"></span>`}
function renderGarden(){garden.innerHTML=herbs.map((h,i)=>`<button class="plot ${h.unlocked?'':'locked'} ${h.grow>=100?'ready':''}" data-herb="${i}" type="button" aria-label="${h.name}"><span class="soil"></span><span class="herb h${h.sprite}" style="--grow:${h.unlocked?(.62+.38*Math.min(1,h.grow/100)):.62}"></span></button>`).join('')}
function renderProducts(){const shown=[0,1,2,3,4];productRow.innerHTML=shown.map((i)=>`<button class="product" data-product="${i}" type="button" aria-label="商品${i+1}"><span class="equip jar eq-jar" aria-hidden="true"></span>${herbSpan(i,'product-herb')}<span class="stock">${products[i]}</span></button>`).join('')}
function renderCustomers(){const wants=[0,1,2];customerRow.innerHTML=wants.map((h,i)=>`<button class="customer-card" data-customer="${i}" type="button"><span class="face"></span><span><span class="customer-name">お客さん${i+1}</span><span class="want">希望 ${herbSpan(h)}</span></span></button>`).join('')}
function renderStatus(){moneyEl.textContent=money;timeEl.textContent=String(Math.floor(minutes/60)%24).padStart(2,'0')+':'+String(minutes%60).padStart(2,'0');dateEl.textContent=day+'日目';basketCount.textContent=raw;$$('.station').forEach(b=>{const k=b.dataset.station;b.classList.toggle('locked',!tools[k]);if(work[k]!=null)b.style.setProperty('--p',work[k]+'%')})}
function say(t){message.textContent=t}
function collect(i,manual=false){const h=herbs[i];if(!h.unlocked)return;if(h.grow<100){if(manual){h.grow=Math.min(100,h.grow+18);say(h.name+'に手をかけました')}return}h.grow=0;h.harvest++;raw++;say(h.name+'を収穫しました');renderGarden();renderStatus()}
function processOne(){if(raw<=0)return;const route=tools.chop&&tools.mortar?['drying','chop','mortar','cauldron']:tools.chop?['drying','chop','cauldron']:['drying','cauldron'];for(const k of route)work[k]=Math.min(100,work[k]+28);const done=route.every(k=>work[k]>=100);if(done){route.forEach(k=>work[k]=0);raw--;processed++;const idx=processed%Math.min(5,herbs.filter(h=>h.unlocked).length);products[idx]++;say('商品が1つ完成しました');renderProducts()}renderStatus()}
function sell(i,manual=false){if(products[i]<=0)return false;products[i]--;money+=12+i*3;say(manual?'商品を手渡しました':'商品が売れました');renderProducts();renderStatus();return true}
function autoTick(){minutes+=10;if(minutes>=24*60){minutes-=24*60;day++}herbs.forEach((h,i)=>{if(!h.unlocked)return;h.grow=Math.min(100,h.grow+3+(i%3));if(h.grow>=100)collect(i)});processOne();if(Math.random()<.45){for(let i=0;i<products.length;i++){if(sell(i))break}}renderGarden();renderStatus()}
function openBook(){renderBook();$('#bookShade').hidden=false;$('#bookPanel').hidden=false}
function closeBook(){$('#bookShade').hidden=true;$('#bookPanel').hidden=true}
function renderBook(){$$('.tab').forEach(t=>t.classList.toggle('active',t.dataset.tab===activeTab));const c=$('#bookContent');if(activeTab==='seeds'){c.innerHTML=herbs.map((h,i)=>`<div class="book-item">${herbSpan(i)}<div><div class="name">${h.name}</div><div class="desc">${h.unlocked?'植え付け済み':'庭に追加する種'}</div></div><button class="buy" data-buy-seed="${i}" ${h.unlocked||money<h.seedCost?'disabled':''}>${h.unlocked?'所持':h.seedCost+'G'}</button></div>`).join('')}else if(activeTab==='tools'){c.innerHTML=['chop','mortar'].map(k=>`<div class="book-item"><span class="equip eq-${k}"></span><div><div class="name">${k==='chop'?'刻み台':'乳鉢'}</div><div class="desc">${tools[k]?'設置済み':'調合工程を増やす'}</div></div><button class="buy" data-buy-tool="${k}" ${tools[k]||money<toolCost[k]?'disabled':''}>${tools[k]?'設置済':toolCost[k]+'G'}</button></div>`).join('')}else{c.innerHTML=recipes.map((r,i)=>`<div class="book-item"><span class="equip eq-book"></span><div><div class="name">${r.name}</div><div class="desc">${r.unlocked?'読了':'新しい商品候補'}</div></div><button class="buy" data-buy-recipe="${i}" ${r.unlocked||money<r.cost?'disabled':''}>${r.unlocked?'読了':r.cost+'G'}</button></div>`).join('')}}
$('#bookButton').addEventListener('click',openBook);$('#bookClose').addEventListener('click',closeBook);$('#bookShade').addEventListener('click',closeBook);$$('.tab').forEach(t=>t.addEventListener('click',()=>{activeTab=t.dataset.tab;renderBook()}));
$('#bookContent').addEventListener('click',e=>{const seed=e.target.closest('[data-buy-seed]');if(seed){const h=herbs[+seed.dataset.buySeed];if(!h.unlocked&&money>=h.seedCost){money-=h.seedCost;h.unlocked=true;h.grow=0;say(h.name+'の種を植えました');renderGarden();renderStatus();renderBook()}return}const tool=e.target.closest('[data-buy-tool]');if(tool){const k=tool.dataset.buyTool;if(!tools[k]&&money>=toolCost[k]){money-=toolCost[k];tools[k]=true;say((k==='chop'?'刻み台':'乳鉢')+'を設置しました');renderStatus();renderBook()}return}const rec=e.target.closest('[data-buy-recipe]');if(rec){const r=recipes[+rec.dataset.buyRecipe];if(!r.unlocked&&money>=r.cost){money-=r.cost;r.unlocked=true;say('レシピを覚えました');renderStatus();renderBook()}}});
garden.addEventListener('click',e=>{const b=e.target.closest('[data-herb]');if(b)collect(+b.dataset.herb,true)});productRow.addEventListener('click',e=>{const b=e.target.closest('[data-product]');if(b)sell(+b.dataset.product,true)});customerRow.addEventListener('click',()=>{for(let i=0;i<products.length;i++){if(sell(i,true))return}say('まだ渡せる商品がありません')});$$('.station').forEach(b=>b.addEventListener('click',()=>{const k=b.dataset.station;if(!tools[k]){say('本から道具を買うと使えます');return}if(k==='basket'){say('収穫したハーブ '+raw);return}work[k]=Math.min(100,(work[k]||0)+22);say(b.querySelector('small').textContent+'を手伝いました');renderStatus()}));
renderGarden();renderProducts();renderCustomers();renderStatus();setInterval(autoTick,2200);
})();